spring.application.name=todolist

spring.datasource.url=jdbc:postgresql://localhost:5432/todolist_db
spring.datasource.username=postgres
spring.datasource.password=864578

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
